#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum OpCode {
    PushConst = 0x00,
    PushInt8 = 0x01,
    PushTrue = 0x02,
    PushFalse = 0x03,
    PushType = 0x04,
    Drop = 0x10,
    Clear = 0x11,
    Dup = 0x12,
    Swap = 0x13,
    Rot = 0x14,
    Over = 0x15,
    Roll = 0x16,
    Pick = 0x17,
    Add = 0x20,
    Sub = 0x21,
    Mul = 0x22,
    Div = 0x23,
    Neg = 0x24,
    Eq = 0x25,
    Gt = 0x26,
    Lt = 0x27,
    And = 0x28,
    Or = 0x29,
    Not = 0x2A,
    ToInt = 0x30,
    ToString = 0x31,
    ToBool = 0x32,
    ToChar = 0x33,
    TypeOf = 0x34,
    StoreGlobal = 0x50,
    LoadGlobal = 0x51,
    Eval = 0x52,
    Return = 0x62,
    Halt = 0x63,
}

impl OpCode {
    pub fn from_byte(byte: u8) -> Result<Self, String> {
        match byte {
            0x00 => Ok(Self::PushConst),
            0x01 => Ok(Self::PushInt8),
            0x02 => Ok(Self::PushTrue),
            0x03 => Ok(Self::PushFalse),
            0x04 => Ok(Self::PushType),
            0x10 => Ok(Self::Drop),
            0x11 => Ok(Self::Clear),
            0x12 => Ok(Self::Dup),
            0x13 => Ok(Self::Swap),
            0x14 => Ok(Self::Rot),
            0x15 => Ok(Self::Over),
            0x16 => Ok(Self::Roll),
            0x17 => Ok(Self::Pick),
            0x20 => Ok(Self::Add),
            0x21 => Ok(Self::Sub),
            0x22 => Ok(Self::Mul),
            0x23 => Ok(Self::Div),
            0x24 => Ok(Self::Neg),
            0x25 => Ok(Self::Eq),
            0x26 => Ok(Self::Gt),
            0x27 => Ok(Self::Lt),
            0x28 => Ok(Self::And),
            0x29 => Ok(Self::Or),
            0x2A => Ok(Self::Not),
            0x30 => Ok(Self::ToInt),
            0x31 => Ok(Self::ToString),
            0x32 => Ok(Self::ToBool),
            0x33 => Ok(Self::ToChar),
            0x34 => Ok(Self::TypeOf),
            0x50 => Ok(Self::StoreGlobal),
            0x51 => Ok(Self::LoadGlobal),
            0x52 => Ok(Self::Eval),
            0x62 => Ok(Self::Return),
            0x63 => Ok(Self::Halt),
            _ => Err(format!("unknown opcode 0x{byte:02x}")),
        }
    }
}
